
GET http://localhost:8080/api/blogs
###
POST http://localhost:8080/api/blogs
Content-Type: application/json

{
    "title": "Some News",
    "author": "John Doe",
    "url": "www.example.com",
    "likes":100 
 }