# Get the list of person
GET http://127.0.0.1:3000/api/persons/


###
# POST a new entry

POST http://127.0.0.1:3000/api/persons HTTP/1.1
Content-Type: application/json

{"name": "Lifia", "number": "1234567879"}

###
# TEST - No entry
POST http://127.0.0.1:3000/api/persons HTTP/1.1
Content-Type: application/json

{"name": "", "number": ""}

###
# TEST - Name already exist
POST http://127.0.0.1:3000/api/persons HTTP/1.1
Content-Type: application/json

{"name": "Arto Hellas", "number": "13236586"}

###
# Get a person using an ID
GET http://127.0.0.1:3000/api/persons/1 

###

# Delete a specific phonebook entry

DELETE http://127.0.0.1:3000/api/persons/1